---
- hosts: "{{ host | default('localhost') }}"
  become: yes
  become_user: "root"
  vars_files:
    - "roles/requirements/vars/main.yml"
  roles:
    - role: requirements
      tags: ["requirements"]
    - role: work
      tags: ["work"]
      become: yes
      become_user: "{{ ansible_env.SUDO_USER }}"
    - role: fedora
      tags: ["fedora"]
    - role: gnome
      tags: ["gnome"]
