---
- name: Remove Fedora Docker dnf packages
  dnf:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- rpm_key: key=https://download.docker.com/linux/fedora/gpg
    state=present

- copy: src=docker-ce.repo 
    dest=/etc/yum.repos.d/docker-ce.repo
    owner=root group=root mode=644

- name: Install Docker CE
  dnf:
    state: installed
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- group: name=docker system=yes

- user: name=docker group=docker create_home=no

- name: Append group docker to "{{ ansible_env.SUDO_USER }}"
  user: 
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes

- name: Start Docker CE
  systemd: 
    name: docker.service
    enabled: yes
    daemon_reload: yes
    state: started

- name: Install Docker Compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64"
    force: yes
    sha256sum: "{{ docker_compose.sha256sum }}"
    mode: u+x
