---
- name: Clone Fedy
  git:
    repo: "git@github.com:rpmfusion-infra/fedy.git"
    dest: "/home/{{ ansible_env.USERNAME }}/Workstation/fedy"
    remote: upstream
    clone: yes
    update: yes
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install Jetbrains Toolbox
  command: "sh /home/{{ ansible_env.USERNAME }}/Workstation/fedy/plugins/jetbrains-toolbox.plugin/install.sh"
  args:
    creates: /opt/jetbrains-toolbox/

- name: Install Postman
  command: "sh /home/{{ ansible_env.USERNAME }}/Workstation/fedy/plugins/postman.plugin/install.sh"
  args:
    creates: /opt/Postman

- name: Disable mouse acceleration
  command: "sh /home/{{ ansible_env.USERNAME }}/Workstation/fedy/plugins/mouse.plugin/setup.sh"
  args:
    creates: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf

- name: Install Microsoft TrueType fonts
  command: "sh /home/{{ ansible_env.USERNAME }}/Workstation/fedy/plugins/msttcorefonts.plugin/install.sh"
  args:
    creates: /var/cache/fedy/mscorefonts

- name: Install Pulseaudio Bluetooth
  command: "sh /home/{{ ansible_env.USERNAME }}/Workstation/fedy/plugins/pulseaudio-module-bluetooth-freeworld.plugin/install.sh"
