---
- name: Remove Fedora Kubectl dnf packages
  dnf:
    state: absent
    name:
      - kubernetes-client

- rpm_key: key=https://packages.cloud.google.com/yum/doc/yum-key.gpg
    state=present

- rpm_key: key=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state=present

- copy: src=kubernetes.repo 
    dest=/etc/yum.repos.d/kubernetes.repo
    owner=root group=root mode=644

- name: Install Kubectl
  dnf:
    state: installed
    name:
      - kubectl

- name: Install Kubectx
  get_url:
    dest: /usr/local/bin/kubectx
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/{{ kubectx.version }}/kubectx"
    force: yes
    mode: a+x

- name: Install Kubens
  get_url:
    dest: /usr/local/bin/kubens
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/{{ kubectx.version }}/kubens"
    force: yes
    mode: a+x

- name: Install  Minikube
  get_url:
    dest: /usr/local/bin/minikube
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    force: yes
    mode: a+x

- name: Creates "/opt/kail/{{ kail.version }}" directory
  file:
    path: "/opt/kail/{{ kail.version }}"
    state: directory
    mode: 0775

- name: Install Kail
  unarchive:
    src: https://github.com/boz/kail/releases/download/v{{ kail.version }}/kail_{{ kail.version }}_linux_amd64.tar.gz
    remote_src: yes
    dest: "/opt/kail/{{ kail.version }}"
    creates: "/opt/kail/{{ kail.version }}/linux-amd64"

- name: Copy Kail
  copy:
    dest: /usr/local/bin
    src: "/opt/kail/{{ kail.version }}/kail"
    force: yes
    mode: a+x

- name: Creates "/opt/helm/{{ helm.version }}" directory
  file:
    path: "/opt/helm/{{ helm.version }}"
    state: directory
    mode: 0775

- name: Install Helm CLI
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-linux-amd64.tar.gz
    remote_src: yes
    dest: "/opt/helm/{{ helm.version }}"
    creates: "/opt/helm/{{ helm.version }}/linux-amd64"

- name: Copy Helm CLI
  copy:
    dest: /usr/local/bin
    src: "/opt/helm/{{ helm.version }}/linux-amd64/helm"
    force: yes
    mode: a+x
