---
- rpm_key: key=https://packages.microsoft.com/keys/microsoft.asc
    state=present

- copy: src=microsoft-vscode.repo 
    dest=/etc/yum.repos.d/vscode.repo
    owner=root group=root mode=644

- name: Install Visual Studio Code
  dnf: pkg=code state=installed

- name: Install vscode extensions
  command: code --install-extension {{ item }}
  with_items:
    - k--kato.intellij-idea-keybindings
    - codezombiech.gitignore
    - cstuder.gitlab-ci-validator
    - DavidAnson.vscode-markdownlint
    - fatihacet.gitlab-workflow
    - file-icons.file-icons
    - joaompinto.asciidoctor-vscode
    - jspolancor.presentationmode
    - jvandyke.vscode-circleci
    - karunamurti.haml
    - mikestead.dotenv
    - redhat.vscode-yaml
    - shanoor.vscode-nginx
    - streetsidesoftware.code-spell-checker
    - timonwong.shellcheck
    - vscoss.vscode-ansible
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
