---
dnf_packages:
  - ack
  - ansible
  - autokey-gtk
  - curl
  - dconf-editor
  - dbus-x11
  - direnv
  - git
  - git-extras
  - glances
  - golang
  - gnome-tweak-tool
  - meld
  - inkspace
  - gimp
  - transmission
  - wireshark
  - wireshark-cli
  - hddtemp
  - htop
  - httpie
  - iotop
  - jq
  - mosh
  - nautilus-open-terminal
  - ncdu
  - openssh-server
  - pv
  - python-setuptools
  - remmina
  - rootsh
  - rubygems
  - system-storage-manager
  - the_silver_searcher
  - tmux
  - tmuxinator
  - tsocks
  - tree
  - weechat
  - xclip
  - zsh
  - terminator
  - dnf-plugins-core
  - fuse-sshfs
  - vim-enhanced
  - gnomebaker
  - autojump
  - autojump-zsh
  - torbrowser-launcher
  - java-11-openjdk
  - java-11-openjdk-devel
  - java-latest-openjdk
  - java-latest-openjdk-devel

rpmfusion_packages:
  - gstreamer1-libav
  - gstreamer1-plugins-good
  - gstreamer1-vaapi
  - vlc
