---
pip_packages:
  - beets
  - virtualenv
  - ps_mem
  - cheat
  - yq
  - awscli

worspace_dirs:
  - kafka
  - debezium
  - php
  - java
  - golang
  - fedora
  - js
  - presentations

kubectx:
  version: v0.6.3

docker_compose:
  version: 1.24.0
  sha256sum: bee6460f96339d5d978bb63d17943f773e1a140242dfa6c941d5e020a302c91b

worspace_repos:
  - { group: 'debezium', dir: 'debezium', repo: 'git@github.com:debezium/debezium.git' }
  - { group: 'debezium', dir: 'debezium-examples', repo: 'git@github.com:debezium/debezium-examples.git' }
  - { group: 'debezium', dir: 'debezium-docker-images', repo: 'git@github.com:debezium/docker-images.git' }
  - { group: 'debezium', dir: 'debezium.github.io', repo: 'git@github.com:debezium/debezium.github.io.git' }
  - { group: 'kafka', dir: 'kafka', repo: 'git@github.com:apache/kafka.git' }
  - { group: 'kafka', dir: 'ksql', repo: 'git@github.com:confluentinc/ksql.git' }
  - { group: 'kafka', dir: 'kafka-streams-examples', repo: 'git@github.com:confluentinc/kafka-streams-examples.git' }
  - { group: 'kafka', dir: 'cp-docker-images', repo: 'git@github.com:confluentinc/cp-docker-images.git' }
  - { group: 'kafka', dir: 'cp-helm-charts', repo: 'git@github.com:confluentinc/cp-helm-charts.git' }
  - { group: 'kafka', dir: 'kafka-rest', repo: 'git@github.com:confluentinc/kafka-rest.git' }
  - { group: 'fedora', dir: 'fedy', repo: 'git@github.com:fedy/fedy.git' }

ansible_python_interpreter: "/usr/bin/python3"
